spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
application:
  security:
    jwt:
      secret-key: 0524D677071733676397924422A452D462D4A6D4E71537538772F423F462848
      expiration: 86400000
      refresh-token:
        expiration: 604800000
server:
  port: 5000
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 12345678
    key-password: 12345678
